### ISSUE TITLE
误触非按键区域使候选词上屏

### ISSUE THREAD

**Issue by VillagerTom** [gurecn/YuyanIme#41]
拼音全键，字母A左侧和字母L右侧空白区域，误触会使候选词直接上屏。

**Comment by gurecn** [comment]
已复现该问题，感谢您的反馈，我会尽快修复。

**Comment by gurecn** [comment]
[雨燕输入法v20240907.08](https://github.com/gurecn/YuyanIme/releases/tag/v20240907.08)已修复该问题，感谢您的反馈，请体验。

**Comment by VillagerTom** [comment]
坏了，Android 7.1.2闪退


```
FATAL EXCEPTION: ThreadPoolUtils-singleton-thread-1
Process: com.yuyan.pinyin.release, PID: 8365
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:200)
	at android.os.Handler.<init>(Handler.java:114)
	at android.content.ClipboardManager$2.<init>(ClipboardManager.java:69)
	at android.content.ClipboardManager.<init>(ClipboardManager.java:69)
	at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:228)
	at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:227)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:860)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:801)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1512)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:659)
	at ot0.J0(SourceFile:241)
	at ub.run(SourceFile:360)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by gurecn** [comment]
有没有触发机制？还是使用就崩溃？

**Comment by VillagerTom** [comment]
> 有没有触发机制？还是使用就崩溃？

打开就崩溃

**Comment by VillagerTom** [comment]
> > 有没有触发机制？还是使用就崩溃？
> 
> 打开就崩溃

从系统设置把雨燕设为默认输入法则会不停报崩溃：![截屏_20240907_172138.jpg](https://github.com/user-attachments/assets/984b8542-0427-454d-a100-33216da4c42a)

**Comment by gurecn** [comment]
收到，这个问题我会在下个版本解决，期间辛苦您回退到上个版本。感谢您的支持。

**Comment by gurecn** [comment]
最新版本[v20240930.16](https://github.com/gurecn/YuyanIme/releases/tag/v20240930.16)已修复剪贴板相关异常，邀请您的体验，期待您的反馈。
